version: '3'

services:

  postgres:
    container_name: conexao_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: "tasks"
      POSTGRES_PASSWORD: "senha123"
    ports:
      - "5436:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - default
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "tasks@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "8085:80"
    depends_on:
      - postgres
    networks:
      - default
    restart: always

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile-python
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - default
    restart: always

networks:
  default:
    name: tasks
